### ISSUE TITLE
Create data model

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#1]
### Assumptions
- we will use MySQL with SQLAlchemy

### Acceptance Criteria
- all entities are listed
- all attributes of each entity are listed
- all relations between entities are identified
- If using RDBMS, database normalization rules should be followed

**Comment by liondon** [comment]
1. promotions
- PK_ID
- title
- description
- promo code (optional)
- start date
- end date
- active
- FK_promotionTypeID (buy x get y free, a% off, etc.) -- for storing/communicating the computation logic
- related arguments ([x=1, y=1], [a=10], etc.) -- for storing/communicating the computation logic

2. promotion_products
- PK_ID
- FK_promotionID
- FK_productID

3. promotionTypes -- for storing/communicating the computation logic
- PK_ID
- description

**Comment by liondon** [comment]
It is also said in the class material that stories should NOT include detailed design.
> For sprint planning, Epics should be broken down into smaller stories, but not so small that you have moved into detailed design.

So maybe this story is actually about **designing** and creating the data model? As long as the schema is not too bizarre, we could always add new columns when some new function needs it.

**Comment by VickySteeves** [comment]
> designing and creating the data model

Yes @nspektor and I agree that this story is about designing and making the data model. So a part of this would be meeting as a dev team & adding in the computation logic (setting the shopping cart team up to do some math!) like you've outlined above.

Here are some types of promotions we might expect and are good to plan:

- buy X get Y free: looks in shopping cart to see if there are X amount of a certain product, and if there is >= X, put Y free product in the cart. Another option is for the consumer to add X+Y products to the cart, and then we discount Y of them.
-  buy X get % off
- sitewide X% off
- category or product is X% off
- Spend $XX get $YY off total
- XX% off the entire purchase

Another thing to consider is when there are promo codes for sales (buy X get Y free) and when it's automatically applied (e.g. sitewide or product-based). We think this means there might be more fields needed for `promotionTypes`, that represent (for instance) X and Y (like we listed above).

**Comment by VickySteeves** [comment]
So as we were going through the other stories, we realized that having start-date, end-date, and active was a bit redundant. We might consider having either just the boolean `active` or the `start-date` and `end-date`. @nspektor & I think the latter makes more sense (doing it by date).

**Comment by VickySteeves** [comment]
We (@nspektor & I) discussed whether everything should have a promocode, whether or not its a "sitewide" discount (in which case, we would automatically apply the discount and users wouldn't need to enter anything special) or its a product or specialty promo where a code is necessary (like 'BOGO' for buy 1 get 1 free).

This is something we might need to discuss as a team though, because it would drastically change the data model.

**Comment by nspektor** [comment]
Decision: every promotion has a promo code, and we can get rid of the `active` key

**Comment by nspektor** [comment]
Some idea for the schema, not sure how to store/communicate the computation logic yet.

1. promotions
- PK_ID
- title
- description
- promo code
- start date
- end date
- FK_promotionTypeID (buy x get y free, a% off, etc.) -- for storing/communicating the computation logic
- related arguments ([x=1, y=1], [a=10], etc.) -- for storing/communicating the computation logic

2. promotion_products
- PK_ID (composite of FKs)
- FK_promotionID
- FK_productID

3. promotionTypes -- for storing/communicating the computation logic
- PK_ID
- description 
- X
- Y
