### ISSUE TITLE
Refactor Read endpoint with Flask-RESTPlus

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#102]
**As a** Developer

**I need** to implement Flask-RESTPlus

**So that** I could generate Swagger Doc with less effort

### Assumptions
- we're following the ﬁle layout outlined in `lab-flask-restplus-swagger` repo

### Acceptance Criteria
- Make sure that all HTTP errors return json error messages and not html. 
- Make sure no 500 errors when throwing bad data 
- Make sure that your Flask-RESTPlus implementation still works like the original. the same test cases should still work as expected. 
- Make sure to add Swagger annotation as well

**Comment by sukumarh** [comment]
Changes committed as a part of the PR #111 .
