### ISSUE TITLE
Increase our PyLint score to 9/10

### ISSUE THREAD

**Issue by nspektor** [2020-nyu-devops/promotions#124]
**As a** Developer

**I need** well formatted and linted code

**So that** our code is easy to read and looks nice throughout the codebase (and we pass this class)

### Assumptions
- We can run black on all of our files to fix glaring lint issues
- then we might have to fix a lot of the others manually

### Acceptance Criteria
- a score of 9/10 when running pylint on our whole codebase

**Comment by VickySteeves** [comment]
This issue as fixed by #126
