### ISSUE TITLE
Integrate Travis CI with the repository

### ISSUE THREAD

**Issue by Kristin01** [2020-nyu-devops/promotions#37]
**As** a developer,
 **I need** to set up Travis CI to monitor the GitHub repository for push and pull requests,
**So that** the system could do automated testing when someone pushes to master or issues a pull request.

**Assumptions:**
Set up Travis CI to monitor the GitHub repository for push and pull requests.

**Acceptance Criteria:**
When someone pushes to master or issues a pull request, Travis CI would monitor that so as to automatically run tests.

**Comment by sukumarh** [comment]
![image](https://user-images.githubusercontent.com/15267877/97378347-8cb99400-1898-11eb-9d7c-e779825b973e.png)
