### ISSUE TITLE
Tests for error-handlers

### ISSUE THREAD

**Issue by VickySteeves** [2020-nyu-devops/promotions#43]
### Assumptions
- There are error handlers in `service.py` that do not have test cases in `test_services.py` (e.g. 405, 415)

### Acceptance Criteria
- After running `nosetests` you verify that test coverage has increased to all lines of code where there is an error handler

**Comment by sukumarh** [comment]
https://github.com/2020-nyu-devops/promotions/pull/29#issuecomment-713591409

Code for adding HTTP_400_BAD_REQUEST
