### ISSUE TITLE
Invite teammates to IBM cloud

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#49]
### Assumptions
- we are following the instructions on `00-invite-to-ibm-cloud.pdf` under NYUClasses > Resource
- we might need our github organization owner (Vicky) to do this, so that later on we could link our cloud service to our repo. (This is not 100% sure.)

### Acceptance Criteria
- Everyone on the team can access our cloud service

**Comment by liondon** [comment]
To review this issue, please login to your IBM cloud account, and do the following:
1. switch to my account with the account dropdown 
2. click Manage > Account > Cloud Foundry org
3. then you should see "2020-nyu-devops"
![image](https://user-images.githubusercontent.com/59273037/97614953-06fd2c00-19f1-11eb-8b74-1df93a322a91.png)

**Comment by Kristin01** [comment]
I login to my IBM Cloud and follow the steps as showed above, and see "2020-nyu-devops". That's great.
