### ISSUE TITLE
Add Action: apply best promotion

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#5]
### Assumptions
- Products are in the shop cart
- Promo codes are necessary for all promotions, including site-wide and product-based ones

### Acceptance Criteria
- Shop cart sends over a request body with the shopping cart data (all products, prices, and user-entered promo codes) to `promotions/apply`
- Respond with a list of promotions that can be applied, and the total discount for the entire cart
- Shop cart then applies that discount and the customer gets their promotion

**Comment by nspektor** [comment]
Note: we should talk to the shop cart team to see how their data is structured
