### ISSUE TITLE
Create a Python Flask Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#50]
### Assumptions
- we're using `Dallas` (US South) for the region of our cloud service.
- we're following the instructions given in the lecture on Oct 28
- we're using the following naming format:
Use the singular version of your resource name (i.e. `promotion`) preﬁxed by `nyu-` and suﬃxed by `-service-f20`. So, ours would be: `nyu-promotion-service-f20`. (The full URL will then be `nyu-promotion-service-f20.us-south.cf.appdomain.cloud`)

### Acceptance Criteria
**When** I access the URL, 
**Then** I can access the hello-world Flask app I created

**Comment by liondon** [comment]
check https://nyu-promotion-service-f20.us-south.cf.appdomain.cloud/ to review this issue.

**Comment by Kristin01** [comment]
looks good.
