### ISSUE TITLE
Update Vagrantfile for IBM Cloud CLI

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#51]
### Assumptions
- we're following the example in `lab-bluemix-cf` repo

### Acceptance Criteria
**When** I type `ibmcloud dev help` command in our VM
**Then** the output lists the usage instructions, the current version, and the supported commands to verify it's been installed successfully.

**Comment by sukumarh** [comment]
Working!

![image](https://user-images.githubusercontent.com/15267877/98045150-04864200-1df6-11eb-8684-daf7655b8144.png)
