### ISSUE TITLE
Set up two stage CD pipeline to unit test and deploy to dev

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#54]
### Assumptions
- we're setting up this on our IBM Cloud service
- we're following the instructions in lecture on Oct 28.

### Acceptance Criteria
**When** I push my application to IBM Cloud
**Then** It will go through the unit tests and be deployed automatically to our dev environment

**Comment by liondon** [comment]
The pipeline is set up, but the deploy will fail now, because we haven't add `Procfile` and all the other files for pushing our app to cloud.
![image](https://user-images.githubusercontent.com/59273037/98050908-b88cca80-1e00-11eb-9efa-41e630776372.png)

![image](https://user-images.githubusercontent.com/59273037/98051149-4072d480-1e01-11eb-9540-f02cf4d8ce75.png)

**Comment by VickySteeves** [comment]
Looks good! Thanks!
