### ISSUE TITLE
Add Integration Test and Deploy to Prod stages into CI/CD Pipeline

### ISSUE THREAD

**Issue by nspektor** [2020-nyu-devops/promotions#56]
**As a** Developer
**I need to** make sure behavior of the service is tested automatically before deploy to production
**So that** we can make sure the service will behave as expected on production environment.

### Assumptions
- BDD scenarios have been set up.

### Acceptance Criteria
- BDD tests run before deploy to production

**Comment by liondon** [comment]
I just realized I misunderstood what this story was about, lol. Sorry about that. The original story is actually about config Travis CI to also run BDD tests when a PR merged to Master branch. I created a new story for it. #99

**Comment by nspektor** [comment]
Yep, verified that the pipeline works
