### ISSUE TITLE
Create a database service & connect it with our Cloud Foundry app

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#57]
### Assumptions
- we're using ElephantSQL for our app cause we use PostgreSQL

### Acceptance Criteria
**When** I check the IBM GUI manage console for our app, 
**Then** I can see our ElephantSQL service listed at `connections` page. The following screen shot is an example:
![image.png](https://images.zenhubusercontent.com/5f7a9739a1698e7923e2e17c/c788b4a6-41fd-4d6a-b8d8-6b2559805625)

**Comment by liondon** [comment]
Here's the steps I took:

1. set up a server at https://www.elephantsql.com/
![image](https://user-images.githubusercontent.com/59273037/97624379-6103ee80-19fd-11eb-8bb2-7ecb40cc7695.png)

2. use the command in class material `07-PlatformAsAService.pdf`-p.137 to set up the User Provide Service at our IBM Cloud Foundry org
`cf cups ElephantSQL -p {"url":"postgres://<username>:<password>@lallah.db.elephantsql.com:5432/<database>"}`

3.  connect ElephantSQL to our application following the same steps as in the material for Cloudant
![image](https://user-images.githubusercontent.com/59273037/97625070-6ca3e500-19fe-11eb-83f8-fef38c1d143d.png)

**Comment by sukumarh** [comment]
ElephantSQL service is visible in the connections of the Cloud Foundry app.
