### ISSUE TITLE
Assign privileges to teammates on IBM Cloud

### ISSUE THREAD

**Issue by liondon** [2020-nyu-devops/promotions#65]
### Assumptions
- we're using Access Group
- we're following instructions on NYUClasses

### Acceptance Criteria
**When** I use my personal account to login to our team account,
**Then** I can provision resources (e.g. cloudant) on the team account.

**Comment by liondon** [comment]
After logging into your personal IBM Cloud account, you should be able to switch to `Ling-I Huang's Account (lih238@cims.nyu.edu)`, create a Cloudant resource there, and delete it.

**Comment by VickySteeves** [comment]
This works! I am going to close it.
