### ISSUE TITLE
BDD Scenario: Create promotion

### ISSUE THREAD

**Issue by sukumarh** [2020-nyu-devops/promotions#71]
**As a** Customer/Stakeholder

**I need** a BDD test for the CREATE endpoint.

**So that** I can verify the endpoint works as expected.

### Assumptions
- The dependent steps are present in the ``` promotion_steps.py ```.
- If products are included, the products should be present in the database.

### Acceptance Criteria
- The following **feature** is tested.
    - Visit home page.
    - Create a promotion.
    - Read the specific promotion.

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201122-075601 "deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201122-075601") to [dev](https://console.bluemix.net/apps/42c5c4c9-a7f2-472a-bfb1-add0f77b8a15?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:dev"), including commit b950080cf99b1115e249ce8de8695de4135e7dff

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252 "deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252") to [prod](https://console.bluemix.net/apps/30a9e46b-e89b-4c2e-930e-53e6242584de?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:prod"), including commit b950080cf99b1115e249ce8de8695de4135e7dff
