### ISSUE TITLE
BDD Scenario: List promotions

### ISSUE THREAD

**Issue by nspektor** [2020-nyu-devops/promotions#76]
**As a** Customer

**I need** a BDD test for the endpoint that lists all of the promotions

**So that** I can verify the endpoint works as expected

### Assumptions
- The dependent steps are present in the ``` promotion_steps.py ```.
- we have some sample data
- we are following gherkin syntax and using behave as shown in the class example

### Acceptance Criteria
- **Given** there are a few promotions in the database
- **When** I Visit home page 
- **And** click to see a list of all promotions
- **Then** I see all of the promotions

**Comment by VickySteeves** [comment]
Whoever picks up this issue will need to add a button in the UI to list all our promotions, also.
