### ISSUE TITLE
Load Sample Data

### ISSUE THREAD

**Issue by sukumarh** [2020-nyu-devops/promotions#77]
**As a** Customer/Stakeholder

**I need** to be able to view sample data.

**So that** I can access different query and best promotion operations without having to use multiple CREATE operations.

### Assumptions
- Sample data would be populated when the application is deployed. 
- This should contain both product and promotion data.

### Acceptance Criteria
- The sample data is present when I load the application and open the Single Page UI for the first time.

**Comment by VickySteeves** [comment]
We decided to close this because it's not necessary for the sprints/project work.
